/*
  Copyright 2019 www.dev5.cn, Inc. dev5@qq.com
 
  This file is part of X-MSG-IM.
 
  X-MSG-IM is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  X-MSG-IM is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
 
  You should have received a copy of the GNU Affero General Public License
  along with X-MSG-IM.  If not, see <https://www.gnu.org/licenses/>.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net-x-msg-xsc-http.proto

package x.msg.pb;

public final class XmsgXscHttpPb {
  private XmsgXscHttpPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface XmsgImHttpRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:XmsgImHttpRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *error code.
     * </pre>
     *
     * <code>uint32 ret = 1;</code>
     */
    int getRet();

    /**
     * <pre>
     *description.
     * </pre>
     *
     * <code>string desc = 2;</code>
     */
    java.lang.String getDesc();
    /**
     * <pre>
     *description.
     * </pre>
     *
     * <code>string desc = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <pre>
     *response message name.
     * </pre>
     *
     * <code>string msg = 3;</code>
     */
    java.lang.String getMsg();
    /**
     * <pre>
     *response message name.
     * </pre>
     *
     * <code>string msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <pre>
     *response message data.
     * </pre>
     *
     * <code>bytes dat = 4;</code>
     */
    com.google.protobuf.ByteString getDat();
  }
  /**
   * <pre>
   *xsc-http协议响应报文.
   * </pre>
   *
   * Protobuf type {@code XmsgImHttpRsp}
   */
  public  static final class XmsgImHttpRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:XmsgImHttpRsp)
      XmsgImHttpRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use XmsgImHttpRsp.newBuilder() to construct.
    private XmsgImHttpRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private XmsgImHttpRsp() {
      ret_ = 0;
      desc_ = "";
      msg_ = "";
      dat_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private XmsgImHttpRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              ret_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 34: {

              dat_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return x.msg.pb.XmsgXscHttpPb.internal_static_XmsgImHttpRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return x.msg.pb.XmsgXscHttpPb.internal_static_XmsgImHttpRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp.class, x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp.Builder.class);
    }

    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <pre>
     *error code.
     * </pre>
     *
     * <code>uint32 ret = 1;</code>
     */
    public int getRet() {
      return ret_;
    }

    public static final int DESC_FIELD_NUMBER = 2;
    private volatile java.lang.Object desc_;
    /**
     * <pre>
     *description.
     * </pre>
     *
     * <code>string desc = 2;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *description.
     * </pre>
     *
     * <code>string desc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object msg_;
    /**
     * <pre>
     *response message name.
     * </pre>
     *
     * <code>string msg = 3;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *response message name.
     * </pre>
     *
     * <code>string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DAT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString dat_;
    /**
     * <pre>
     *response message data.
     * </pre>
     *
     * <code>bytes dat = 4;</code>
     */
    public com.google.protobuf.ByteString getDat() {
      return dat_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ret_ != 0) {
        output.writeUInt32(1, ret_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
      }
      if (!dat_.isEmpty()) {
        output.writeBytes(4, dat_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ret_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, ret_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
      }
      if (!dat_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, dat_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp)) {
        return super.equals(obj);
      }
      x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp other = (x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp) obj;

      boolean result = true;
      result = result && (getRet()
          == other.getRet());
      result = result && getDesc()
          .equals(other.getDesc());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && getDat()
          .equals(other.getDat());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RET_FIELD_NUMBER;
      hash = (53 * hash) + getRet();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + DAT_FIELD_NUMBER;
      hash = (53 * hash) + getDat().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *xsc-http协议响应报文.
     * </pre>
     *
     * Protobuf type {@code XmsgImHttpRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:XmsgImHttpRsp)
        x.msg.pb.XmsgXscHttpPb.XmsgImHttpRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return x.msg.pb.XmsgXscHttpPb.internal_static_XmsgImHttpRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return x.msg.pb.XmsgXscHttpPb.internal_static_XmsgImHttpRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp.class, x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp.Builder.class);
      }

      // Construct using x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ret_ = 0;

        desc_ = "";

        msg_ = "";

        dat_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return x.msg.pb.XmsgXscHttpPb.internal_static_XmsgImHttpRsp_descriptor;
      }

      public x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp getDefaultInstanceForType() {
        return x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp.getDefaultInstance();
      }

      public x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp build() {
        x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp buildPartial() {
        x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp result = new x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp(this);
        result.ret_ = ret_;
        result.desc_ = desc_;
        result.msg_ = msg_;
        result.dat_ = dat_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp) {
          return mergeFrom((x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp other) {
        if (other == x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp.getDefaultInstance()) return this;
        if (other.getRet() != 0) {
          setRet(other.getRet());
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getDat() != com.google.protobuf.ByteString.EMPTY) {
          setDat(other.getDat());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ret_ ;
      /**
       * <pre>
       *error code.
       * </pre>
       *
       * <code>uint32 ret = 1;</code>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <pre>
       *error code.
       * </pre>
       *
       * <code>uint32 ret = 1;</code>
       */
      public Builder setRet(int value) {
        
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *error code.
       * </pre>
       *
       * <code>uint32 ret = 1;</code>
       */
      public Builder clearRet() {
        
        ret_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <pre>
       *description.
       * </pre>
       *
       * <code>string desc = 2;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *description.
       * </pre>
       *
       * <code>string desc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *description.
       * </pre>
       *
       * <code>string desc = 2;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *description.
       * </pre>
       *
       * <code>string desc = 2;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *description.
       * </pre>
       *
       * <code>string desc = 2;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <pre>
       *response message name.
       * </pre>
       *
       * <code>string msg = 3;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *response message name.
       * </pre>
       *
       * <code>string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *response message name.
       * </pre>
       *
       * <code>string msg = 3;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *response message name.
       * </pre>
       *
       * <code>string msg = 3;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *response message name.
       * </pre>
       *
       * <code>string msg = 3;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dat_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *response message data.
       * </pre>
       *
       * <code>bytes dat = 4;</code>
       */
      public com.google.protobuf.ByteString getDat() {
        return dat_;
      }
      /**
       * <pre>
       *response message data.
       * </pre>
       *
       * <code>bytes dat = 4;</code>
       */
      public Builder setDat(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *response message data.
       * </pre>
       *
       * <code>bytes dat = 4;</code>
       */
      public Builder clearDat() {
        
        dat_ = getDefaultInstance().getDat();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:XmsgImHttpRsp)
    }

    // @@protoc_insertion_point(class_scope:XmsgImHttpRsp)
    private static final x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp();
    }

    public static x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<XmsgImHttpRsp>
        PARSER = new com.google.protobuf.AbstractParser<XmsgImHttpRsp>() {
      public XmsgImHttpRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new XmsgImHttpRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<XmsgImHttpRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<XmsgImHttpRsp> getParserForType() {
      return PARSER;
    }

    public x.msg.pb.XmsgXscHttpPb.XmsgImHttpRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_XmsgImHttpRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_XmsgImHttpRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030net-x-msg-xsc-http.proto\"D\n\rXmsgImHttp" +
      "Rsp\022\013\n\003ret\030\001 \001(\r\022\014\n\004desc\030\002 \001(\t\022\013\n\003msg\030\003 " +
      "\001(\t\022\013\n\003dat\030\004 \001(\014B\031\n\010x.msg.pbB\rXmsgXscHtt" +
      "pPbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_XmsgImHttpRsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_XmsgImHttpRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_XmsgImHttpRsp_descriptor,
        new java.lang.String[] { "Ret", "Desc", "Msg", "Dat", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
